export const JOB_ROLES = [
  "Executive Chef",
  "Head Chef",
  "Sous Chef",
  "Chef de Partie",
  "Commis Chef",
  "Pastry Chef",
  "Bakery Chef",
  "Pizza Chef",
  "Grill Chef",
  "Indian Chef",
  "Arabic Chef",
  "Chinese Chef",
  "Tandoor Chef",
  "Kitchen Helper",
  "Kitchen Steward",
  "Dishwasher",
  "Butcher",
  "Sandwich Maker",
  "Juice Maker",
  "Restaurant Manager",
  "Assistant Restaurant Manager",
  "Café Manager",
  "Outlet Manager",
  "Floor Supervisor",
  "Captain",
  "Steward",
  "Senior Steward",
  "Host",
  "Hostess",
  "Cashier",
  "Food Runner",
  "Busser",
  "Order Taker",
  "Drive-Thru Staff",
  "Barista",
  "Bartender",
  "Mixologist",
  "Bar Supervisor",
  "Bar Manager",
  "Beverage Manager",
  "Hotel Manager",
  "Front Office Manager",
  "Receptionist",
  "Guest Relations Executive",
  "Bell Boy",
  "Concierge",
  "Reservation Agent",
  "Night Auditor",
  "Housekeeping Supervisor",
  "Housekeeping Staff",
  "Laundry Attendant",
  "Room Attendant",
  "Operations Manager",
  "Area Manager",
  "General Manager",
  "HR Executive",
  "Recruitment Coordinator",
  "Accountant",
  "Purchase Manager",
  "Store Keeper",
  "Inventory Controller",
  "Admin Executive",
  "Delivery Driver",
  "Bike Rider",
  "Dispatch Executive",
  "Warehouse Assistant",
  "Logistics Coordinator",
  "Catering Manager",
  "Banquet Supervisor",
  "Event Coordinator",
  "Banquet Staff",
  "Cleaner",
  "Maintenance Technician",
  "Electrician",
  "Plumber",
  "AC Technician",
  "Security Guard",
  "Other"
];
