import Footer from "./component/layout/Footer";
import Header from "./component/layout/Navbar";

const PrivacyPolicy = () => {
    return (
        <div>
            <Header />
            <div className="mt-28 p-3 text-white">
                <h1 className="text-white text-3xl font-black mb-2">Privacy Policy</h1>
                <p className="text-sm opacity-80">Last Updated: July 2026 &middot; Effective Immediately</p>
                <p className="text-sm opacity-80 mt-1">A product of Hoss Global Inc. &middot; India</p>

                <h2 className="mt-6 text-xl font-bold text-white">Overview</h2>
                <p className="mt-2">
                    This Privacy Policy describes how Jobrito ("we", "us", "our", "you", "your", "Jobrito") &mdash; a product of Hoss Global Inc. &mdash; collects, uses, stores, and protects your personal data when you use the Jobrito app or website (jobrito.com), or communicate with us.
                </p>
                <p className="mt-2">
                    Jobrito is a hospitality-focused talent and recruitment platform connecting professionals, employers, and opportunities across the HoReCa (Hotel, Restaurant, and Catering) industry. By accessing or using our platform, you agree to the practices described in this policy.
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">Interpretation and Definitions</h2>
                <h3 className="mt-4 text-lg font-semibold text-white">Interpretation</h3>
                <p className="mt-2">
                    The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3 className="mt-4 text-lg font-semibold text-white">Definitions</h3>
                <p className="mt-2">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                    <li>
                        <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
                    </li>
                    <li>
                        <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                    </li>
                    <li>
                        <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to jobrito.
                    </li>
                    <li>
                        <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                    </li>
                    <li>
                        <strong>Country</strong> refers to: India
                    </li>
                    <li>
                        <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.
                    </li>
                    <li>
                        <strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.
                    </li>
                    <li>
                        We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.
                    </li>
                    <li>
                        <strong>Service</strong> refers to the Website.
                    </li>
                    <li>
                        <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                    </li>
                    <li>
                        <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </li>
                    <li>
                        <strong>Website</strong> refers to jobrito, accessible from{" "}
                        <a href="http://jobrito.com/" target="_blank" rel="noopener noreferrer" className="underline">
                            http://jobrito.com/
                        </a>
                        .
                    </li>
                    <li>
                        <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                    </li>
                </ul>

                <h2 className="mt-8 text-2xl font-black text-white border-b pb-2 border-slate-700">Collecting and Using Your Personal Data</h2>

                <h2 className="mt-6 text-xl font-bold text-white">1. Personal Data We Collect</h2>
                <p className="mt-2">
                    We collect personal data to operate the platform, match talent with employers, and deliver our recruitment matching services.
                </p>

                <h3 className="mt-4 text-lg font-semibold text-white">Talent (Jobseeker) Information</h3>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Full name, email address, phone number</li>
                    <li>Employment history</li>
                    <li>Professional skills</li>
                    <li>Job preferences, availability, and salary expectations</li>
                    <li>Profile photo (optional)</li>
                    <li>LinkedIn or public professional social network profile links</li>
                    <li>Application activity and platform interactions</li>
                </ul>

                <h3 className="mt-4 text-lg font-semibold text-white">Employer / Business Information</h3>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Company name and registration details</li>
                    <li>Contact person name, email, and phone number</li>
                    <li>Job descriptions and role requirements</li>
                    <li>Hiring preferences and shortlist activity</li>
                </ul>

                <h3 className="mt-4 text-lg font-semibold text-white">Technical &amp; Platform Data:</h3>
                <p className="mt-1">Collected automatically when you use our app or visit jobrito.com:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>IP address and device identifiers</li>
                    <li>Browser type and operating system</li>
                    <li>Approximate location</li>
                    <li>App usage activity</li>
                    <li>Cookies and similar tracking technologies</li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">2. How We Collect Personal Data</h2>
                <p className="mt-2">We collect data through:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Account registration and profile creation on the Jobrito app</li>
                    <li>Job applications submitted through the platform</li>
                    <li>Job role submission</li>
                    <li>Email, phone, or in-app communication</li>
                    <li>LinkedIn or public professional social profile imports (with your consent)</li>
                    <li>Employer onboarding and job posting flows</li>
                    <li>Cookies, analytics tools, and app usage tracking</li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">3. Purpose of Processing Personal Data</h2>
                <p className="mt-2">We process personal data to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Match job seekers with relevant hospitality opportunities</li>
                    <li>Connect employers with qualified candidates</li>
                    <li>Power platform features such as Chef Connect</li>
                    <li>Communicate platform updates, job alerts, and relevant opportunities (with consent)</li>
                    <li>Manage employer accounts, job postings</li>
                    <li>Improve platform performance, features, and user experience</li>
                    <li>Ensure platform security and fraud prevention</li>
                    <li>Comply with applicable requirements.</li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">4. Legal Basis for Processing</h2>
                <p className="mt-2">Our processing is based on:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Your consent &mdash; account registration, profile creation, job applications, and cookies</li>
                    <li>Contractual necessity &mdash; providing the recruitment and talent matching services you signed up for</li>
                    <li>Legitimate interest &mdash; improving the platform, preventing fraud, and operating our business</li>
                    <li>Legal obligation &mdash; compliance with applicable requirements and regulations in India.</li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">5. Data Sharing</h2>
                <p className="mt-2">We never sell personal data. We may share information only in limited circumstances:</p>

                <h3 className="mt-4 text-lg font-semibold text-white">For Talent (Jobseekers)</h3>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Potential employers &mdash; only when you apply for a role or explicitly consent to profile sharing</li>
                    <li>Assessment or verification partners (where applicable)</li>
                </ul>

                <h3 className="mt-4 text-lg font-semibold text-white">For Employers / Businesses</h3>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Candidates you have shortlisted or requested to view</li>
                </ul>

                <h3 className="mt-4 text-lg font-semibold text-white">General Operations</h3>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Cloud hosting and infrastructure providers</li>
                    <li>Communication and email delivery platforms</li>
                    <li>App analytics and performance monitoring tools</li>
                    <li>Government or regulatory authorities, if required by law</li>
                </ul>
                <p className="mt-2">
                    All third-party service providers are required to handle data securely and in compliance with applicable data protection regulations.
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">6. International Data Transfers</h2>
                <p className="mt-2">
                    Jobrito operates across India &amp; Saudi Arabia. Some service providers may process data outside your home country. Where international transfers occur, we ensure:
                </p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Adequate data protection safeguards are in place</li>
                    <li>Contractual commitments that ensure confidentiality and security</li>
                    <li>Compliance with applicable national data protection frameworks</li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">7. Data Retention</h2>
                <p className="mt-2">We retain personal data only for as long as necessary for:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Active account management and talent matching</li>
                    <li>Ongoing employer and candidate relationships</li>
                    <li>Compliance with applicable requirements and regulations</li>
                    <li>Resolving disputes and enforcing our agreements</li>
                </ul>
                <p className="mt-2">
                    When data is no longer required, it is securely deleted or anonymized. You may request deletion of your data at any time (see Your Rights below).
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">8. Your Rights</h2>
                <p className="mt-2">You have the right to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Access your personal data held by Jobrito</li>
                    <li>Correct or update inaccurate information</li>
                    <li>Request deletion of your data (subject to legal obligations)</li>
                    <li>Withdraw consent at any time without affecting prior processing</li>
                    <li>Object to processing for direct marketing or certain other purposes</li>
                    <li>Understand how your data is collected and used</li>
                </ul>
                <p className="mt-2">
                    To exercise any of these rights, contact us at:{" "}
                    <a href="mailto:jobritoapp@gmail.com" className="underline">
                        jobritoapp@gmail.com
                    </a>
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">9. Cookies &amp; Tracking Technologies</h2>
                <p className="mt-2">Jobrito uses cookies and similar technologies to:</p>
                <ul className="list-disc pl-6 mt-2 space-y-1">
                    <li>Keep you logged in and remember your preferences</li>
                    <li>Analyse app and website usage for improvement</li>
                    <li>Deliver relevant job recommendations</li>
                    <li>Enhance platform security</li>
                </ul>
                <p className="mt-2">
                    You may manage or disable cookies through your browser or device settings. Disabling certain cookies may affect platform functionality.
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">10. Usage Data</h2>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                    <li>
                        <strong>Website analytics data</strong> (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, this allows us to analyze trends while respecting privacy principles.
                    </li>
                    <li>
                        <strong>Server logs</strong> (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.
                    </li>
                    <li>
                        Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.
                    </li>
                    <li>
                        We may retain Personal Data beyond the periods stated above for different reasons.
                    </li>
                </ul>

                <h2 className="mt-6 text-xl font-bold text-white">11. Children's Privacy</h2>
                <p className="mt-2">
                    Jobrito is a professional platform intended for individuals aged 18 and above. We do not knowingly collect personal data from minors. If we become aware that a minor has created an account, we will promptly delete the associated data.
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">12. Updates to This Policy</h2>
                <p className="mt-2">
                    We may update this Privacy Policy from time to time to reflect changes in our practices, platform features, or legal requirements. Updated policies will be published on this page with a revised "Last Updated" date. We encourage you to review this policy periodically.
                </p>

                <h2 className="mt-6 text-xl font-bold text-white">13. Contact Us</h2>
                <p className="mt-2">
                    For data requests, privacy questions, or concerns: email:{" "}
                    <a href="mailto:jobritoapp@gmail.com" className="underline">
                        jobritoapp@gmail.com
                    </a>
                </p>
            </div>
            <Footer />
        </div>
    );
};

export default PrivacyPolicy;
